  global:
    scrape_interval: 15s
    evaluation_interval: 15s

  scrape_configs:
    - job_name: 'apk-analysis-server'
      static_configs:
        - targets: ['apk-analysis-server:9090']
      metrics_path: '/metrics'


