global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'apk-analysis-server'
    static_configs:
      - targets: ['apk-analysis-server:8080']
    metrics_path: '/metrics/prometheus'

  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
